In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("Dataset/used_cars.csv")
df

,Unnamed: 0,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,Make
0,0,T-Roc,2019,25000,Automatic,13904,Diesel,145,49.6,2.0,VW
1,1,T-Roc,2019,26883,Automatic,4562,Diesel,145,49.6,2.0,VW
2,2,T-Roc,2019,20000,Manual,7414,Diesel,145,50.4,2.0,VW
3,3,T-Roc,2019,33492,Automatic,4825,Petrol,145,32.5,2.0,VW
4,4,T-Roc,2019,22900,Semi-Auto,6500,Petrol,150,39.8,1.5,VW
...,...,...,...,...,...,...,...,...,...,...,...
99182,10663,A3,2020,16999,Manual,4018,Petrol,145,49.6,1.0,Audi
99183,10664,A3,2020,16999,Manual,1978,Petrol,150,49.6,1.0,Audi
99184,10665,A3,2020,17199,Manual,609,Petrol,150,49.6,1.0,Audi
99185,10666,Q3,2017,19499,Automatic,8646,Petrol,150,47.9,1.4,Audi
99186,10667,Q3,2016,15999,Manual,11855,Petrol,150,47.9,1.4,Audi

In [5]:
df.columns

Index(['Unnamed: 0', 'model', 'year', 'price', 'transmission', 'mileage',
       'fuelType', 'tax', 'mpg', 'engineSize', 'Make'],
      dtype='object')

In [6]:
df.isna().sum()

Unnamed: 0      0
model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
Make            0
dtype: int64

In [7]:
df.select_dtypes(include='object')

        model transmission fuelType  Make
0       T-Roc    Automatic   Diesel    VW
1       T-Roc    Automatic   Diesel    VW
2       T-Roc       Manual   Diesel    VW
3       T-Roc    Automatic   Petrol    VW
4       T-Roc    Semi-Auto   Petrol    VW
...       ...          ...      ...   ...
99182      A3       Manual   Petrol  Audi
99183      A3       Manual   Petrol  Audi
99184      A3       Manual   Petrol  Audi
99185      Q3    Automatic   Petrol  Audi
99186      Q3       Manual   Petrol  Audi

[99187 rows x 4 columns]

In [8]:
df.select_dtypes(include="number")

       Unnamed: 0  year  price  mileage  tax   mpg  engineSize
0               0  2019  25000    13904  145  49.6         2.0
1               1  2019  26883     4562  145  49.6         2.0
2               2  2019  20000     7414  145  50.4         2.0
3               3  2019  33492     4825  145  32.5         2.0
4               4  2019  22900     6500  150  39.8         1.5
...           ...   ...    ...      ...  ...   ...         ...
99182       10663  2020  16999     4018  145  49.6         1.0
99183       10664  2020  16999     1978  150  49.6         1.0
99184       10665  2020  17199      609  150  49.6         1.0
99185       10666  2017  19499     8646  150  47.9         1.4
99186       10667  2016  15999    11855  150  47.9         1.4

[99187 rows x 7 columns]

In [9]:
df = df.drop(columns=['Unnamed: 0'])

In [10]:
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize,Make
0,T-Roc,2019,25000,Automatic,13904,Diesel,145,49.6,2.0,VW
1,T-Roc,2019,26883,Automatic,4562,Diesel,145,49.6,2.0,VW
2,T-Roc,2019,20000,Manual,7414,Diesel,145,50.4,2.0,VW
3,T-Roc,2019,33492,Automatic,4825,Petrol,145,32.5,2.0,VW
4,T-Roc,2019,22900,Semi-Auto,6500,Petrol,150,39.8,1.5,VW
...,...,...,...,...,...,...,...,...,...,...
99182,A3,2020,16999,Manual,4018,Petrol,145,49.6,1.0,Audi
99183,A3,2020,16999,Manual,1978,Petrol,150,49.6,1.0,Audi
99184,A3,2020,17199,Manual,609,Petrol,150,49.6,1.0,Audi
99185,Q3,2017,19499,Automatic,8646,Petrol,150,47.9,1.4,Audi
99186,Q3,2016,15999,Manual,11855,Petrol,150,47.9,1.4,Audi

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x = df.drop("price",axis=1)
y = df["price"]

In [13]:
x

,model,year,transmission,mileage,fuelType,tax,mpg,engineSize,Make
0,T-Roc,2019,Automatic,13904,Diesel,145,49.6,2.0,VW
1,T-Roc,2019,Automatic,4562,Diesel,145,49.6,2.0,VW
2,T-Roc,2019,Manual,7414,Diesel,145,50.4,2.0,VW
3,T-Roc,2019,Automatic,4825,Petrol,145,32.5,2.0,VW
4,T-Roc,2019,Semi-Auto,6500,Petrol,150,39.8,1.5,VW
...,...,...,...,...,...,...,...,...,...
99182,A3,2020,Manual,4018,Petrol,145,49.6,1.0,Audi
99183,A3,2020,Manual,1978,Petrol,150,49.6,1.0,Audi
99184,A3,2020,Manual,609,Petrol,150,49.6,1.0,Audi
99185,Q3,2017,Automatic,8646,Petrol,150,47.9,1.4,Audi
99186,Q3,2016,Manual,11855,Petrol,150,47.9,1.4,Audi

In [14]:
y

0        25000
1        26883
2        20000
3        33492
4        22900
         ...
99182    16999
99183    16999
99184    17199
99185    19499
99186    15999
Name: price, Length: 99187, dtype: int64

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=42)

In [16]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [17]:
nums_col = ["year","mileage","tax","mpg","engineSize"]

cats_col = ["model","transmission","fuelType","Make"]

In [18]:
nums_pipeline = StandardScaler()
nums_pipeline

StandardScaler()

In [19]:
cats_pipeline = OneHotEncoder(handle_unknown="ignore")
cats_pipeline

OneHotEncoder(handle_unknown='ignore')

In [20]:
preprocessor = ColumnTransformer([
    ("nums",nums_pipeline,nums_col),
    ("cats",cats_pipeline,cats_col)

])

In [21]:
preprocessor

ColumnTransformer(transformers=[('nums', StandardScaler(),
                                 ['year', 'mileage', 'tax', 'mpg',
                                  'engineSize']),
                                ('cats', OneHotEncoder(handle_unknown='ignore'),
                                 ['model', 'transmission', 'fuelType',
                                  'Make'])])

In [22]:
linear_reg_pipeline = Pipeline([
    ("preprocessor",preprocessor),
    ("model",LinearRegression())
])

In [23]:
linear_reg_pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('nums', StandardScaler(),
                                                  ['year', 'mileage', 'tax',
                                                   'mpg', 'engineSize']),
                                                 ('cats',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['model', 'transmission',
                                                   'fuelType', 'Make'])])),
                ('model', LinearRegression())])

In [24]:
lr_predict = linear_reg_pipeline.predict(x_test)
lr_predict

array([ 6338.03219382,  9423.77880116,  9223.76581342, ...,
       40892.43829394, 24782.31521396, 26645.29396995], shape=(32732,))

In [25]:

print("mae: ",mean_absolute_error(y_test,lr_predict))
print("mse: ",mean_squared_error(y_test,lr_predict))
print("r2: ",r2_score(y_test,lr_predict))

mae:  2263.438673988865
mse:  13788435.423583236
r2:  0.8557596146424891

In [27]:
svm_pipeline = Pipeline([
    ("preprocessor",preprocessor),
    ("model",SVR())

])

In [28]:
svm_pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('nums', StandardScaler(),
                                                  ['year', 'mileage', 'tax',
                                                   'mpg', 'engineSize']),
                                                 ('cats',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['model', 'transmission',
                                                   'fuelType', 'Make'])])),
                ('model', SVR())])

In [30]:
svm_predict =svm_pipeline.predict(x_test)

In [32]:
print("mae: ",mean_absolute_error(y_test,svm_predict))
print("mse: ",mean_squared_error(y_test,svm_predict))
print("r2: ",r2_score(y_test,svm_predict))

mae:  4750.29114501721
mse:  64594152.38637173
r2:  0.32428262193428803

In [33]:
from sklearn.neighbors import KNeighborsRegressor

In [34]:
kn_pipeline = Pipeline([
    ("preprocessor",preprocessor),
    ("model",KNeighborsRegressor(n_neighbors=5))
])

In [35]:
kn_pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('nums', StandardScaler(),
                                                  ['year', 'mileage', 'tax',
                                                   'mpg', 'engineSize']),
                                                 ('cats',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['model', 'transmission',
                                                   'fuelType', 'Make'])])),
                ('model', KNeighborsRegressor())])

In [37]:
kn_predict = kn_pipeline.predict(x_test)

In [38]:
print("mae: ",mean_absolute_error(y_test,kn_predict))
print("mse: ",mean_squared_error(y_test,kn_predict))
print("r2: ",r2_score(y_test,kn_predict))

mae:  1234.08358181596
mse:  4925120.129745815
r2:  0.948478474633059

In [40]:
dt_pipeline = Pipeline([
    ("preprocessor",preprocessor),
    ("model",DecisionTreeRegressor())
])

In [41]:
dt_pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('nums', StandardScaler(),
                                                  ['year', 'mileage', 'tax',
                                                   'mpg', 'engineSize']),
                                                 ('cats',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['model', 'transmission',
                                                   'fuelType', 'Make'])])),
                ('model', DecisionTreeRegressor())])

In [43]:
dt_predict = dt_pipeline.predict(x_test)

In [45]:
print("mae: ",mean_absolute_error(y_test,dt_predict))
print("mse: ",mean_squared_error(y_test,dt_predict))
print("r2: ",r2_score(y_test,dt_predict))

mae:  1443.2493468089854
mse:  6624956.425770894
r2:  0.9306965410886638

In [46]:
rf_pipeline = Pipeline([
    ("preprocessor",preprocessor),
    ("model",RandomForestRegressor())
])

In [47]:
rf_pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('nums', StandardScaler(),
                                                  ['year', 'mileage', 'tax',
                                                   'mpg', 'engineSize']),
                                                 ('cats',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['model', 'transmission',
                                                   'fuelType', 'Make'])])),
                ('model', RandomForestRegressor())])

In [49]:
rf_predict = rf_pipeline.predict(x_test)

In [50]:
print("mae: ",mean_absolute_error(y_test,rf_predict))
print("mse: ",mean_squared_error(y_test,rf_predict))
print("r2: ",r2_score(y_test,rf_predict))

mae:  1157.1753708104302
mse:  4193693.686941759
r2:  0.9561299034376851

In [51]:
from sklearn.ensemble import GradientBoostingRegressor
gb_pipeline = Pipeline([
    ("preprocessor",preprocessor),
    ("model",GradientBoostingRegressor())
])

In [52]:
gb_pipeline.fit(x_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('nums', StandardScaler(),
                                                  ['year', 'mileage', 'tax',
                                                   'mpg', 'engineSize']),
                                                 ('cats',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['model', 'transmission',
                                                   'fuelType', 'Make'])])),
                ('model', GradientBoostingRegressor())])

In [53]:
gb_predict = gb_pipeline.predict(x_test)

In [54]:
print("mae: ",mean_absolute_error(y_test,gb_predict))
print("mse: ",mean_squared_error(y_test,gb_predict))
print("r2: ",r2_score(y_test,gb_predict))

mae:  2118.8065212859274
mse:  9992122.446317999
r2:  0.8954727242126941

In [55]:
param_grid_rf = {
    "model__n_estimators":[100,200],
    'model__max_depth':[10,20
                        ]
}

In [56]:
from sklearn.model_selection import GridSearchCV

In [59]:
grid_rf = GridSearchCV(
    rf_pipeline,
    param_grid_rf,
    cv=3,
    scoring="r2",
    n_jobs=-1
)

In [60]:
grid_rf.fit(x_train,y_train)

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('nums',
                                                                         StandardScaler(),
                                                                         ['year',
                                                                          'mileage',
                                                                          'tax',
                                                                          'mpg',
                                                                          'engineSize']),
                                                                        ('cats',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['model',
                                                                          'transmission',
                                                                          'fuelType',
                                                                          'Make'])])),
                                       ('model', RandomForestRegressor())]),
             n_jobs=-1,
             param_grid={'model__max_depth': [10, 20],
                         'model__n_estimators': [100, 200]},
             scoring='r2')

In [61]:
print("best parameters: ",grid_rf.best_params_)
print("best cv score: ",grid_rf.best_score_)

best parameters:  {'model__max_depth': 20, 'model__n_estimators': 100}
best cv score:  0.9553572623031331

In [62]:
rf_predict = grid_rf.predict(x_test)

In [63]:
print("mse:",mean_squared_error(y_test,rf_predict))
print("mae:",mean_absolute_error(y_test,rf_predict))
print("r2:",r2_score(y_test,rf_predict))

mse: 4427268.682203857
mae: 1198.8403039477118
r2: 0.9536864828253029

In [65]:
print(rf_pipeline)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('nums', StandardScaler(),
                                                  ['year', 'mileage', 'tax',
                                                   'mpg', 'engineSize']),
                                                 ('cats',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['model', 'transmission',
                                                   'fuelType', 'Make'])])),
                ('model', RandomForestRegressor())])

TESTING WITH UNKNOWN DATA

In [67]:
new_car = pd.DataFrame({
    "model":["Golf"],
    "year":[2018],
    "transmission":["manual"],
    "mileage":[30000],
    "fuelType":["petrol"],
    "tax":[150],
    "mpg":[50.0],
    "engineSize":[1.4],
    "Make":["Volkswagen"]

})

In [68]:
prediction = rf_pipeline.predict(new_car)
print(prediction[0])

16755.05

In [69]:
import joblib
joblib.dump(rf_pipeline,"car_price_model.pkl")

['car_price_model.pkl']

In [70]:
model = joblib.load("car_price_model.pkl")
prediction = model.predict(new_car)
print(prediction[0])

16755.05